theme: minima
title: My Title
author: Jeffrey S. Haemer
description: A test for GitHub pages as a blog site.
ess: escargo
pee: pterodactyl
avatar: https://observer.com/wp-content/uploads/sites/2/2015/10/crumblrg.jpg
